name = "idkaboutbytes/cframeutils"
version = "1.0.1"
description = "CFrameUtils package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/cframeutils"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "sourcemap.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.1" }
Math = { repo = "idkaboutbytes/math", rev = "v1.0.1" }
